#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 05 12:57:02 IST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim vio_wrapper_behav -key {Behavioral:sim_1:Functional:vio_wrapper} -tclbatch vio_wrapper.tcl -log simulate.log"
xsim vio_wrapper_behav -key {Behavioral:sim_1:Functional:vio_wrapper} -tclbatch vio_wrapper.tcl -log simulate.log

