# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adi/repo/notes/sem3/ELD2024_LAB/lab7/lab7.srcs/sources_1/ip/xfft_03/xfft_03.xci
# IP: The module: 'xfft_03' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adi/repo/notes/sem3/ELD2024_LAB/lab7/lab7.srcs/sources_1/ip/xfft_03/xfft_03_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_03'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/adi/repo/notes/sem3/ELD2024_LAB/lab7/lab7.srcs/sources_1/ip/xfft_03/xfft_03.xci
# IP: The module: 'xfft_03' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adi/repo/notes/sem3/ELD2024_LAB/lab7/lab7.srcs/sources_1/ip/xfft_03/xfft_03_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft_03'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
