require("adi.launch")
require("adi.options")
require("adi.keymaps")
require("adi.highlightOnYank")
spec("adi.colorscheme")
spec("adi.treesitter")
spec("adi.mason")
spec("adi.lspconfig")
spec("adi.cmp")
spec("adi.autopairs")
spec("adi.comment")
-- spec("adi.lualine")
spec("adi.markdownPreview")
spec("adi.markdown")
-- spec("adi.mdeval")
spec("adi.table")
spec("adi.colorizer")
spec("adi.focus")
spec("adi.ibl")
-- spec("adi.wal")
-- spec("adi.hex")
spec("adi.transparent")
-- spec("adi.mdtangle")
require("adi.lazy")
require("adi.init")
require("adi.headlines")
vim.cmd.colorscheme("catppuccin")
-- spec("adi.gitsigns")
-- spec("adi.telescope")
-- spec("adi.dap")
-- spec("adi.dapui")
-- spec("adi.lspsaga")
-- spec("adi.vimbegood")
-- require("adi.colorselect").setup()
