something: graph.cpp
	g++ -o output graph.cpp
	./output

1:
	g++ -o output_1 1.cpp
	./output_1

2:
	g++ -o output_2 2.cpp
	./output_2

3:
	g++ -o output_3 3.cpp
	./output_3

4:
	g++ -o output_4 4.cpp
	./output_4

target: something
