# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adi/repo/notes/sem3/ELD2024_LAB/lab6/lab6.srcs/sources_1/ip/FL_log/FL_log.xci
# IP: The module: 'FL_log' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adi/repo/notes/sem3/ELD2024_LAB/lab6/lab6.srcs/sources_1/ip/FL_log/FL_log_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FL_log'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/adi/repo/notes/sem3/ELD2024_LAB/lab6/lab6.srcs/sources_1/ip/FL_log/FL_log.xci
# IP: The module: 'FL_log' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adi/repo/notes/sem3/ELD2024_LAB/lab6/lab6.srcs/sources_1/ip/FL_log/FL_log_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FL_log'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
