// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FFT,hls_ip_2019_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.399750,HLS_SYN_LAT=197,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=20,HLS_SYN_FF=2270,HLS_SYN_LUT=3892,HLS_VERSION=2019_1}" *)

module FFT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        FFT_input_real_address0,
        FFT_input_real_ce0,
        FFT_input_real_q0,
        FFT_input_imag_address0,
        FFT_input_imag_ce0,
        FFT_input_imag_q0,
        FFT_output_real_address0,
        FFT_output_real_ce0,
        FFT_output_real_we0,
        FFT_output_real_d0,
        FFT_output_real_address1,
        FFT_output_real_ce1,
        FFT_output_real_we1,
        FFT_output_real_d1,
        FFT_output_imag_address0,
        FFT_output_imag_ce0,
        FFT_output_imag_we0,
        FFT_output_imag_d0,
        FFT_output_imag_address1,
        FFT_output_imag_ce1,
        FFT_output_imag_we1,
        FFT_output_imag_d1
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] FFT_input_real_address0;
output   FFT_input_real_ce0;
input  [31:0] FFT_input_real_q0;
output  [2:0] FFT_input_imag_address0;
output   FFT_input_imag_ce0;
input  [31:0] FFT_input_imag_q0;
output  [2:0] FFT_output_real_address0;
output   FFT_output_real_ce0;
output   FFT_output_real_we0;
output  [31:0] FFT_output_real_d0;
output  [2:0] FFT_output_real_address1;
output   FFT_output_real_ce1;
output   FFT_output_real_we1;
output  [31:0] FFT_output_real_d1;
output  [2:0] FFT_output_imag_address0;
output   FFT_output_imag_ce0;
output   FFT_output_imag_we0;
output  [31:0] FFT_output_imag_d0;
output  [2:0] FFT_output_imag_address1;
output   FFT_output_imag_ce1;
output   FFT_output_imag_we1;
output  [31:0] FFT_output_imag_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg FFT_input_real_ce0;
reg FFT_input_imag_ce0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] rev8_address0;
reg    rev8_ce0;
wire   [2:0] rev8_q0;
wire   [3:0] i_fu_136_p2;
reg   [3:0] i_reg_156;
wire    ap_CS_fsm_state2;
wire   [63:0] zext_ln18_fu_142_p1;
reg   [63:0] zext_ln18_reg_161;
wire   [0:0] icmp_ln17_fu_130_p2;
wire    ap_CS_fsm_state3;
reg   [2:0] FFT_rev_real_address0;
reg    FFT_rev_real_ce0;
reg    FFT_rev_real_we0;
wire   [31:0] FFT_rev_real_q0;
reg    FFT_rev_real_ce1;
wire   [31:0] FFT_rev_real_q1;
reg   [2:0] FFT_rev_imag_address0;
reg    FFT_rev_imag_ce0;
reg    FFT_rev_imag_we0;
wire   [31:0] FFT_rev_imag_q0;
reg    FFT_rev_imag_ce1;
wire   [31:0] FFT_rev_imag_q1;
wire    grp_FFT_stages_fu_120_ap_start;
wire    grp_FFT_stages_fu_120_ap_done;
wire    grp_FFT_stages_fu_120_ap_idle;
wire    grp_FFT_stages_fu_120_ap_ready;
wire   [2:0] grp_FFT_stages_fu_120_FFT_input_real_address0;
wire    grp_FFT_stages_fu_120_FFT_input_real_ce0;
wire   [2:0] grp_FFT_stages_fu_120_FFT_input_real_address1;
wire    grp_FFT_stages_fu_120_FFT_input_real_ce1;
wire   [2:0] grp_FFT_stages_fu_120_FFT_input_imag_address0;
wire    grp_FFT_stages_fu_120_FFT_input_imag_ce0;
wire   [2:0] grp_FFT_stages_fu_120_FFT_input_imag_address1;
wire    grp_FFT_stages_fu_120_FFT_input_imag_ce1;
wire   [2:0] grp_FFT_stages_fu_120_FFT_output_real_address0;
wire    grp_FFT_stages_fu_120_FFT_output_real_ce0;
wire    grp_FFT_stages_fu_120_FFT_output_real_we0;
wire   [31:0] grp_FFT_stages_fu_120_FFT_output_real_d0;
wire   [2:0] grp_FFT_stages_fu_120_FFT_output_real_address1;
wire    grp_FFT_stages_fu_120_FFT_output_real_ce1;
wire    grp_FFT_stages_fu_120_FFT_output_real_we1;
wire   [31:0] grp_FFT_stages_fu_120_FFT_output_real_d1;
wire   [2:0] grp_FFT_stages_fu_120_FFT_output_imag_address0;
wire    grp_FFT_stages_fu_120_FFT_output_imag_ce0;
wire    grp_FFT_stages_fu_120_FFT_output_imag_we0;
wire   [31:0] grp_FFT_stages_fu_120_FFT_output_imag_d0;
wire   [2:0] grp_FFT_stages_fu_120_FFT_output_imag_address1;
wire    grp_FFT_stages_fu_120_FFT_output_imag_ce1;
wire    grp_FFT_stages_fu_120_FFT_output_imag_we1;
wire   [31:0] grp_FFT_stages_fu_120_FFT_output_imag_d1;
reg   [3:0] i_0_i_reg_109;
wire    ap_CS_fsm_state4;
reg    grp_FFT_stages_fu_120_ap_start_reg;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln18_1_fu_147_p1;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_FFT_stages_fu_120_ap_start_reg = 1'b0;
end

FFT_rev8 #(
    .DataWidth( 3 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
rev8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(rev8_address0),
    .ce0(rev8_ce0),
    .q0(rev8_q0)
);

FFT_FFT_rev_real #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
FFT_rev_real_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_rev_real_address0),
    .ce0(FFT_rev_real_ce0),
    .we0(FFT_rev_real_we0),
    .d0(FFT_input_real_q0),
    .q0(FFT_rev_real_q0),
    .address1(grp_FFT_stages_fu_120_FFT_input_real_address1),
    .ce1(FFT_rev_real_ce1),
    .q1(FFT_rev_real_q1)
);

FFT_FFT_rev_real #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
FFT_rev_imag_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(FFT_rev_imag_address0),
    .ce0(FFT_rev_imag_ce0),
    .we0(FFT_rev_imag_we0),
    .d0(FFT_input_imag_q0),
    .q0(FFT_rev_imag_q0),
    .address1(grp_FFT_stages_fu_120_FFT_input_imag_address1),
    .ce1(FFT_rev_imag_ce1),
    .q1(FFT_rev_imag_q1)
);

FFT_stages grp_FFT_stages_fu_120(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_FFT_stages_fu_120_ap_start),
    .ap_done(grp_FFT_stages_fu_120_ap_done),
    .ap_idle(grp_FFT_stages_fu_120_ap_idle),
    .ap_ready(grp_FFT_stages_fu_120_ap_ready),
    .FFT_input_real_address0(grp_FFT_stages_fu_120_FFT_input_real_address0),
    .FFT_input_real_ce0(grp_FFT_stages_fu_120_FFT_input_real_ce0),
    .FFT_input_real_q0(FFT_rev_real_q0),
    .FFT_input_real_address1(grp_FFT_stages_fu_120_FFT_input_real_address1),
    .FFT_input_real_ce1(grp_FFT_stages_fu_120_FFT_input_real_ce1),
    .FFT_input_real_q1(FFT_rev_real_q1),
    .FFT_input_imag_address0(grp_FFT_stages_fu_120_FFT_input_imag_address0),
    .FFT_input_imag_ce0(grp_FFT_stages_fu_120_FFT_input_imag_ce0),
    .FFT_input_imag_q0(FFT_rev_imag_q0),
    .FFT_input_imag_address1(grp_FFT_stages_fu_120_FFT_input_imag_address1),
    .FFT_input_imag_ce1(grp_FFT_stages_fu_120_FFT_input_imag_ce1),
    .FFT_input_imag_q1(FFT_rev_imag_q1),
    .FFT_output_real_address0(grp_FFT_stages_fu_120_FFT_output_real_address0),
    .FFT_output_real_ce0(grp_FFT_stages_fu_120_FFT_output_real_ce0),
    .FFT_output_real_we0(grp_FFT_stages_fu_120_FFT_output_real_we0),
    .FFT_output_real_d0(grp_FFT_stages_fu_120_FFT_output_real_d0),
    .FFT_output_real_address1(grp_FFT_stages_fu_120_FFT_output_real_address1),
    .FFT_output_real_ce1(grp_FFT_stages_fu_120_FFT_output_real_ce1),
    .FFT_output_real_we1(grp_FFT_stages_fu_120_FFT_output_real_we1),
    .FFT_output_real_d1(grp_FFT_stages_fu_120_FFT_output_real_d1),
    .FFT_output_imag_address0(grp_FFT_stages_fu_120_FFT_output_imag_address0),
    .FFT_output_imag_ce0(grp_FFT_stages_fu_120_FFT_output_imag_ce0),
    .FFT_output_imag_we0(grp_FFT_stages_fu_120_FFT_output_imag_we0),
    .FFT_output_imag_d0(grp_FFT_stages_fu_120_FFT_output_imag_d0),
    .FFT_output_imag_address1(grp_FFT_stages_fu_120_FFT_output_imag_address1),
    .FFT_output_imag_ce1(grp_FFT_stages_fu_120_FFT_output_imag_ce1),
    .FFT_output_imag_we1(grp_FFT_stages_fu_120_FFT_output_imag_we1),
    .FFT_output_imag_d1(grp_FFT_stages_fu_120_FFT_output_imag_d1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FFT_stages_fu_120_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln17_fu_130_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_FFT_stages_fu_120_ap_start_reg <= 1'b1;
        end else if ((grp_FFT_stages_fu_120_ap_ready == 1'b1)) begin
            grp_FFT_stages_fu_120_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_0_i_reg_109 <= i_reg_156;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_i_reg_109 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_156 <= i_fu_136_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln17_fu_130_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        zext_ln18_reg_161[3 : 0] <= zext_ln18_fu_142_p1[3 : 0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        FFT_input_imag_ce0 = 1'b1;
    end else begin
        FFT_input_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        FFT_input_real_ce0 = 1'b1;
    end else begin
        FFT_input_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_rev_imag_address0 = zext_ln18_reg_161;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        FFT_rev_imag_address0 = grp_FFT_stages_fu_120_FFT_input_imag_address0;
    end else begin
        FFT_rev_imag_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_rev_imag_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        FFT_rev_imag_ce0 = grp_FFT_stages_fu_120_FFT_input_imag_ce0;
    end else begin
        FFT_rev_imag_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FFT_rev_imag_ce1 = grp_FFT_stages_fu_120_FFT_input_imag_ce1;
    end else begin
        FFT_rev_imag_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_rev_imag_we0 = 1'b1;
    end else begin
        FFT_rev_imag_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_rev_real_address0 = zext_ln18_reg_161;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        FFT_rev_real_address0 = grp_FFT_stages_fu_120_FFT_input_real_address0;
    end else begin
        FFT_rev_real_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_rev_real_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        FFT_rev_real_ce0 = grp_FFT_stages_fu_120_FFT_input_real_ce0;
    end else begin
        FFT_rev_real_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        FFT_rev_real_ce1 = grp_FFT_stages_fu_120_FFT_input_real_ce1;
    end else begin
        FFT_rev_real_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        FFT_rev_real_we0 = 1'b1;
    end else begin
        FFT_rev_real_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_FFT_stages_fu_120_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_FFT_stages_fu_120_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        rev8_ce0 = 1'b1;
    end else begin
        rev8_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln17_fu_130_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_FFT_stages_fu_120_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign FFT_input_imag_address0 = zext_ln18_1_fu_147_p1;

assign FFT_input_real_address0 = zext_ln18_1_fu_147_p1;

assign FFT_output_imag_address0 = grp_FFT_stages_fu_120_FFT_output_imag_address0;

assign FFT_output_imag_address1 = grp_FFT_stages_fu_120_FFT_output_imag_address1;

assign FFT_output_imag_ce0 = grp_FFT_stages_fu_120_FFT_output_imag_ce0;

assign FFT_output_imag_ce1 = grp_FFT_stages_fu_120_FFT_output_imag_ce1;

assign FFT_output_imag_d0 = grp_FFT_stages_fu_120_FFT_output_imag_d0;

assign FFT_output_imag_d1 = grp_FFT_stages_fu_120_FFT_output_imag_d1;

assign FFT_output_imag_we0 = grp_FFT_stages_fu_120_FFT_output_imag_we0;

assign FFT_output_imag_we1 = grp_FFT_stages_fu_120_FFT_output_imag_we1;

assign FFT_output_real_address0 = grp_FFT_stages_fu_120_FFT_output_real_address0;

assign FFT_output_real_address1 = grp_FFT_stages_fu_120_FFT_output_real_address1;

assign FFT_output_real_ce0 = grp_FFT_stages_fu_120_FFT_output_real_ce0;

assign FFT_output_real_ce1 = grp_FFT_stages_fu_120_FFT_output_real_ce1;

assign FFT_output_real_d0 = grp_FFT_stages_fu_120_FFT_output_real_d0;

assign FFT_output_real_d1 = grp_FFT_stages_fu_120_FFT_output_real_d1;

assign FFT_output_real_we0 = grp_FFT_stages_fu_120_FFT_output_real_we0;

assign FFT_output_real_we1 = grp_FFT_stages_fu_120_FFT_output_real_we1;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_FFT_stages_fu_120_ap_start = grp_FFT_stages_fu_120_ap_start_reg;

assign i_fu_136_p2 = (i_0_i_reg_109 + 4'd1);

assign icmp_ln17_fu_130_p2 = ((i_0_i_reg_109 == 4'd8) ? 1'b1 : 1'b0);

assign rev8_address0 = zext_ln18_fu_142_p1;

assign zext_ln18_1_fu_147_p1 = rev8_q0;

assign zext_ln18_fu_142_p1 = i_0_i_reg_109;

always @ (posedge ap_clk) begin
    zext_ln18_reg_161[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //FFT
