#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Oct 19 19:21:47 IST 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim Top_FL_TB_behav -key {Behavioral:sim_1:Functional:Top_FL_TB} -tclbatch Top_FL_TB.tcl -log simulate.log"
xsim Top_FL_TB_behav -key {Behavioral:sim_1:Functional:Top_FL_TB} -tclbatch Top_FL_TB.tcl -log simulate.log

