# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adi/repo/notes/sem3/ELD2024_LAB/lab7_hw_2/lab7_hw_2.srcs/sources_1/ip/FL_sqrt/FL_sqrt.xci
# IP: The module: 'FL_sqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adi/repo/notes/sem3/ELD2024_LAB/lab7_hw_2/lab7_hw_2.srcs/sources_1/ip/FL_sqrt/FL_sqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FL_sqrt'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/adi/repo/notes/sem3/ELD2024_LAB/lab7_hw_2/lab7_hw_2.srcs/sources_1/ip/FL_sqrt/FL_sqrt.xci
# IP: The module: 'FL_sqrt' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adi/repo/notes/sem3/ELD2024_LAB/lab7_hw_2/lab7_hw_2.srcs/sources_1/ip/FL_sqrt/FL_sqrt_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FL_sqrt'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
