// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _FFT_HH_
#define _FFT_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "FFT_stages.h"
#include "FFT_rev8.h"
#include "FFT_FFT_rev_real.h"

namespace ap_rtl {

struct FFT : public sc_module {
    // Port declarations 28
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<3> > FFT_input_real_address0;
    sc_out< sc_logic > FFT_input_real_ce0;
    sc_in< sc_lv<32> > FFT_input_real_q0;
    sc_out< sc_lv<3> > FFT_input_imag_address0;
    sc_out< sc_logic > FFT_input_imag_ce0;
    sc_in< sc_lv<32> > FFT_input_imag_q0;
    sc_out< sc_lv<3> > FFT_output_real_address0;
    sc_out< sc_logic > FFT_output_real_ce0;
    sc_out< sc_logic > FFT_output_real_we0;
    sc_out< sc_lv<32> > FFT_output_real_d0;
    sc_out< sc_lv<3> > FFT_output_real_address1;
    sc_out< sc_logic > FFT_output_real_ce1;
    sc_out< sc_logic > FFT_output_real_we1;
    sc_out< sc_lv<32> > FFT_output_real_d1;
    sc_out< sc_lv<3> > FFT_output_imag_address0;
    sc_out< sc_logic > FFT_output_imag_ce0;
    sc_out< sc_logic > FFT_output_imag_we0;
    sc_out< sc_lv<32> > FFT_output_imag_d0;
    sc_out< sc_lv<3> > FFT_output_imag_address1;
    sc_out< sc_logic > FFT_output_imag_ce1;
    sc_out< sc_logic > FFT_output_imag_we1;
    sc_out< sc_lv<32> > FFT_output_imag_d1;


    // Module declarations
    FFT(sc_module_name name);
    SC_HAS_PROCESS(FFT);

    ~FFT();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    FFT_rev8* rev8_U;
    FFT_FFT_rev_real* FFT_rev_real_U;
    FFT_FFT_rev_real* FFT_rev_imag_U;
    FFT_stages* grp_FFT_stages_fu_120;
    sc_signal< sc_lv<5> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<3> > rev8_address0;
    sc_signal< sc_logic > rev8_ce0;
    sc_signal< sc_lv<3> > rev8_q0;
    sc_signal< sc_lv<4> > i_fu_136_p2;
    sc_signal< sc_lv<4> > i_reg_156;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<64> > zext_ln18_fu_142_p1;
    sc_signal< sc_lv<64> > zext_ln18_reg_161;
    sc_signal< sc_lv<1> > icmp_ln17_fu_130_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<3> > FFT_rev_real_address0;
    sc_signal< sc_logic > FFT_rev_real_ce0;
    sc_signal< sc_logic > FFT_rev_real_we0;
    sc_signal< sc_lv<32> > FFT_rev_real_q0;
    sc_signal< sc_logic > FFT_rev_real_ce1;
    sc_signal< sc_lv<32> > FFT_rev_real_q1;
    sc_signal< sc_lv<3> > FFT_rev_imag_address0;
    sc_signal< sc_logic > FFT_rev_imag_ce0;
    sc_signal< sc_logic > FFT_rev_imag_we0;
    sc_signal< sc_lv<32> > FFT_rev_imag_q0;
    sc_signal< sc_logic > FFT_rev_imag_ce1;
    sc_signal< sc_lv<32> > FFT_rev_imag_q1;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_ap_start;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_ap_done;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_ap_idle;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_ap_ready;
    sc_signal< sc_lv<3> > grp_FFT_stages_fu_120_FFT_input_real_address0;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_input_real_ce0;
    sc_signal< sc_lv<3> > grp_FFT_stages_fu_120_FFT_input_real_address1;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_input_real_ce1;
    sc_signal< sc_lv<3> > grp_FFT_stages_fu_120_FFT_input_imag_address0;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_input_imag_ce0;
    sc_signal< sc_lv<3> > grp_FFT_stages_fu_120_FFT_input_imag_address1;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_input_imag_ce1;
    sc_signal< sc_lv<3> > grp_FFT_stages_fu_120_FFT_output_real_address0;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_output_real_ce0;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_output_real_we0;
    sc_signal< sc_lv<32> > grp_FFT_stages_fu_120_FFT_output_real_d0;
    sc_signal< sc_lv<3> > grp_FFT_stages_fu_120_FFT_output_real_address1;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_output_real_ce1;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_output_real_we1;
    sc_signal< sc_lv<32> > grp_FFT_stages_fu_120_FFT_output_real_d1;
    sc_signal< sc_lv<3> > grp_FFT_stages_fu_120_FFT_output_imag_address0;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_output_imag_ce0;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_output_imag_we0;
    sc_signal< sc_lv<32> > grp_FFT_stages_fu_120_FFT_output_imag_d0;
    sc_signal< sc_lv<3> > grp_FFT_stages_fu_120_FFT_output_imag_address1;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_output_imag_ce1;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_FFT_output_imag_we1;
    sc_signal< sc_lv<32> > grp_FFT_stages_fu_120_FFT_output_imag_d1;
    sc_signal< sc_lv<4> > i_0_i_reg_109;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > grp_FFT_stages_fu_120_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > zext_ln18_1_fu_147_p1;
    sc_signal< sc_lv<5> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<5> ap_ST_fsm_state1;
    static const sc_lv<5> ap_ST_fsm_state2;
    static const sc_lv<5> ap_ST_fsm_state3;
    static const sc_lv<5> ap_ST_fsm_state4;
    static const sc_lv<5> ap_ST_fsm_state5;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_FFT_input_imag_address0();
    void thread_FFT_input_imag_ce0();
    void thread_FFT_input_real_address0();
    void thread_FFT_input_real_ce0();
    void thread_FFT_output_imag_address0();
    void thread_FFT_output_imag_address1();
    void thread_FFT_output_imag_ce0();
    void thread_FFT_output_imag_ce1();
    void thread_FFT_output_imag_d0();
    void thread_FFT_output_imag_d1();
    void thread_FFT_output_imag_we0();
    void thread_FFT_output_imag_we1();
    void thread_FFT_output_real_address0();
    void thread_FFT_output_real_address1();
    void thread_FFT_output_real_ce0();
    void thread_FFT_output_real_ce1();
    void thread_FFT_output_real_d0();
    void thread_FFT_output_real_d1();
    void thread_FFT_output_real_we0();
    void thread_FFT_output_real_we1();
    void thread_FFT_rev_imag_address0();
    void thread_FFT_rev_imag_ce0();
    void thread_FFT_rev_imag_ce1();
    void thread_FFT_rev_imag_we0();
    void thread_FFT_rev_real_address0();
    void thread_FFT_rev_real_ce0();
    void thread_FFT_rev_real_ce1();
    void thread_FFT_rev_real_we0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_FFT_stages_fu_120_ap_start();
    void thread_i_fu_136_p2();
    void thread_icmp_ln17_fu_130_p2();
    void thread_rev8_address0();
    void thread_rev8_ce0();
    void thread_zext_ln18_1_fu_147_p1();
    void thread_zext_ln18_fu_142_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
