#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("FFT_input_real_address0", 3, hls_out, 0, "ap_memory", "mem_address", 1),
	Port_Property("FFT_input_real_ce0", 1, hls_out, 0, "ap_memory", "mem_ce", 1),
	Port_Property("FFT_input_real_q0", 32, hls_in, 0, "ap_memory", "mem_dout", 1),
	Port_Property("FFT_input_imag_address0", 3, hls_out, 1, "ap_memory", "mem_address", 1),
	Port_Property("FFT_input_imag_ce0", 1, hls_out, 1, "ap_memory", "mem_ce", 1),
	Port_Property("FFT_input_imag_q0", 32, hls_in, 1, "ap_memory", "mem_dout", 1),
	Port_Property("FFT_output_real_address0", 3, hls_out, 2, "ap_memory", "mem_address", 1),
	Port_Property("FFT_output_real_ce0", 1, hls_out, 2, "ap_memory", "mem_ce", 1),
	Port_Property("FFT_output_real_we0", 1, hls_out, 2, "ap_memory", "mem_we", 1),
	Port_Property("FFT_output_real_d0", 32, hls_out, 2, "ap_memory", "mem_din", 1),
	Port_Property("FFT_output_real_address1", 3, hls_out, 2, "ap_memory", "MemPortADDR2", 1),
	Port_Property("FFT_output_real_ce1", 1, hls_out, 2, "ap_memory", "MemPortCE2", 1),
	Port_Property("FFT_output_real_we1", 1, hls_out, 2, "ap_memory", "MemPortWE2", 1),
	Port_Property("FFT_output_real_d1", 32, hls_out, 2, "ap_memory", "MemPortDIN2", 1),
	Port_Property("FFT_output_imag_address0", 3, hls_out, 3, "ap_memory", "mem_address", 1),
	Port_Property("FFT_output_imag_ce0", 1, hls_out, 3, "ap_memory", "mem_ce", 1),
	Port_Property("FFT_output_imag_we0", 1, hls_out, 3, "ap_memory", "mem_we", 1),
	Port_Property("FFT_output_imag_d0", 32, hls_out, 3, "ap_memory", "mem_din", 1),
	Port_Property("FFT_output_imag_address1", 3, hls_out, 3, "ap_memory", "MemPortADDR2", 1),
	Port_Property("FFT_output_imag_ce1", 1, hls_out, 3, "ap_memory", "MemPortCE2", 1),
	Port_Property("FFT_output_imag_we1", 1, hls_out, 3, "ap_memory", "MemPortWE2", 1),
	Port_Property("FFT_output_imag_d1", 32, hls_out, 3, "ap_memory", "MemPortDIN2", 1),
};
const char* HLS_Design_Meta::dut_name = "FFT";
