webtalk_init -webtalk_dir /home/adi/repo/notes/sem3/ELD2024_LAB/lab8_hw_draft3/lab8_hw_draft3.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2024-11-08 16:40:24" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9idluel9f6fa9ig7l7e9trpbfq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 5900HX with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3038.035 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.140 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1731063635000" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key VivadoVersion -value "2019.1" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1731063635000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1731064224129"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1731064224129"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1731064224129"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1731064224129"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1731064224129"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1731064224129"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1731064224129"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1731064224129"
webtalk_transmit -clientid 2280195851 -regid "" -xml /home/adi/repo/notes/sem3/ELD2024_LAB/lab8_hw_draft3/lab8_hw_draft3.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/adi/repo/notes/sem3/ELD2024_LAB/lab8_hw_draft3/lab8_hw_draft3.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/adi/repo/notes/sem3/ELD2024_LAB/lab8_hw_draft3/lab8_hw_draft3.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
